development:  
  redis_url: http://127.0.0.1:6379
  namespace: framework-dev

test:  
  redis_url: http://127.0.0.1:6379
  namespace: framework-test

production:  
  redis_url: <%= ENV['REDISTOGO_URL'] %>
  namespace: framework
